=== AnthonyFA/CDLCRUSOE/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "max_distance": {
      "type": "integer"
    },
    "path": {
      "type": "object",
      "properties": {
        "apply": {
          "type": "boolean"
        },
        "subnet": {
          "type": "integer"
        },
        "organization": {
          "type": "number"
        },
        "contact": {
          "type": "number"
        }
      },
      "required": [
        "apply",
        "subnet",
        "organization",
        "contact"
      ]
    },
    "os": {
      "type": "object",
      "properties": {
        "apply": {
          "type": "boolean"
        },
        "critical_bound": {
          "type": "number"
        },
        "vendor": {
          "type": "number"
        },
        "product": {
          "type": "number"
        },
        "version": {
          "type": "number"
        },
        "diff_value": {
          "type": "number"
        }
      },
      "required": [
        "apply",
        "critical_bound",
        "vendor",
        "product",
        "version",
        "diff_value"
      ]
    },
    "antivirus": {
      "type": "object",
      "properties": {
        "apply": {
          "type": "boolean"
        },
        "critical_bound": {
          "type": "number"
        },
        "vendor": {
          "type": "number"
        },
        "product": {
          "type": "number"
        },
        "version": {
          "type": "number"
        },
        "diff_value": {
          "type": "number"
        }
      },
      "required": [
        "apply",
        "critical_bound",
        "vendor",
        "product",
        "version",
        "diff_value"
      ]
    },
    "cms": {
      "type": "object",
      "properties": {
        "apply": {
          "type": "boolean"
        },
        "critical_bound": {
          "type": "number"
        },
        "vendor": {
          "type": "number"
        },
        "product": {
          "type": "number"
        },
        "version": {
          "type": "number"
        },
        "require_open_http": {
          "type": "boolean"
        },
        "diff_value": {
          "type": "number"
        }
      },
      "required": [
        "apply",
        "critical_bound",
        "vendor",
        "product",
        "version",
        "require_open_http",
        "diff_value"
      ]
    },
    "net_service": {
      "type": "object",
      "properties": {
        "apply": {
          "type": "boolean"
        },
        "critical_bound": {
          "type": "number"
        },
        "diff_value": {
          "type": "number"
        }
      },
      "required": [
        "apply",
        "critical_bound",
        "diff_value"
      ]
    },
    "cve_cumulative": {
      "type": "object",
      "properties": {
        "apply": {
          "type": "boolean"
        },
        "critical_bound": {
          "type": "number"
        },
        "zero_value": {
          "type": "number"
        }
      },
      "required": [
        "apply",
        "critical_bound",
        "zero_value"
      ]
    },
    "event_cumulative": {
      "type": "object",
      "properties": {
        "apply": {
          "type": "boolean"
        },
        "critical_bound": {
          "type": "number"
        },
        "zero_value": {
          "type": "number"
        }
      },
      "required": [
        "apply",
        "critical_bound",
        "zero_value"
      ]
    }
  },
  "required": [
    "max_distance",
    "path",
    "os",
    "antivirus",
    "cms",
    "net_service",
    "cve_cumulative",
    "event_cumulative"
  ]
}

=== AnthonyFA/CDLCRUSOE/src/backend/config.json
{
    "max_distance": 4,
    "path": {
        "apply": true,
        "subnet": 1,
        "organization": 0.9,
        "contact": 0.8
    },
    "os": {
        "apply": true,
        "critical_bound": 0.17027579,
        "vendor": 0.7,
        "product": 0.2,
        "version": 0.1,
        "diff_value": 0.3
    },
    "antivirus": {
        "apply": true,
        "critical_bound": 0.16666667,
        "vendor": 0.6,
        "product": 0.25,
        "version": 0.15,
        "diff_value": 0.7
    },
    "cms": {
        "apply": true,
        "critical_bound": 0.08161032,
        "vendor": 0.5,
        "product": 0.3,
        "version": 0.2,
        "require_open_http": false,
        "diff_value": 0.8
    },
    "net_service": {
        "apply": true,
        "critical_bound": 0.4,
        "diff_value": 0.7
    },
    "cve_cumulative": {
        "apply": true,
        "critical_bound": 0.29492334,
        "zero_value": 0.9
    },
    "event_cumulative": {
        "apply": true,
        "critical_bound": 0.00036752,
        "zero_value": 0.9
    }
}
